import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  const next = searchParams.get("redirect") ?? "/dashboard";

  if (code) {
    const supabase = await createClient();
    const { error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error) {
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (user) {
        const session = await supabase.auth.getSession();
        const token = session.data.session?.access_token;

        if (token) {
          try {
            const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/users/me`, {
              headers: { Authorization: `Bearer ${token}` },
            });

            if (response.ok) {
              const profile = await response.json();

              // Check if user needs onboarding (username is auto-generated)
              if (isAutoGeneratedUsername(profile.username, user.email)) {
                return NextResponse.redirect(`${origin}/onboarding`);
              }
            }
          } catch {
            // Backend unreachable - continue to dashboard, profile will be created later
          }
        }
      }

      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  // Auth error - redirect to login with error
  return NextResponse.redirect(`${origin}/login?error=auth_callback_error`);
}

function isAutoGeneratedUsername(username: string, email: string | undefined): boolean {
  if (!email) return false;

  // Backend generates username from email prefix: john.doe@gmail.com -> johndoe
  const emailPrefix = email
    .split("@")[0]
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "");

  // Check if username exactly matches email prefix or has a suffix (johndoe_a3k2)
  return username === emailPrefix || username.startsWith(emailPrefix + "_");
}
